[package]
name = "htmx-lsp-server"
version = "0.1.0"
edition = "2021"
description = "lsp server for htmx-lsp"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
log.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
htmx-lsp-util = { version = "0.1", path = "../util" }
maplit = "1.0.2"
nom = "7.1.3"

espionox = { git = "https://github.com/voidKandy/espionox_lib", branch = "stable" }
tokio = { version = "1.28.2", features = ["full"] }
