language_model:
  default_model: "gpt-3.5-turbo-1106"
  api_key: "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"

database:
  host: 127.0.0.1
  port: 6987
  username: "postgres"
  password: ""
  database_name: ""
