language_model:
  default_model: "gpt-3.5-turbo-1106"
  api_key: "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"

database:
  host: 127.0.0.1
  port: 6987
  username: "postgres"
  password: ""
  database_name: ""
